# Generated by Django 4.2.13 on 2024-07-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user',
            new_name='username',
        ),
    ]
