# Generated by Django 4.2.13 on 2024-07-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='appuser',
            name='pic',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='users'),
        ),
    ]
