# Generated by Django 4.2.13 on 2024-07-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_appuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="bio",
            field=models.TextField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="name",
            field=models.CharField(
                help_text="this will be visible to others", max_length=100
            ),
        ),
    ]
