# Generated by Django 4.2.13 on 2024-08-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_appuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="users"),
        ),
    ]
