# Generated by Django 4.2.13 on 2024-07-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField(help_text='in minutes')),
                ('ingredients', models.CharField(help_text='separate ingredients with a comma and a space', max_length=255)),
            ],
        ),
    ]
