# Generated by Django 4.2.13 on 2024-07-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(
                default=list,
                help_text="split into a list of steps like ['1 step', '2 step']",
            ),
        ),
    ]
