# Generated by Django 4.2.13 on 2024-07-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_description_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                help_text="separate ingredients with a comma and a space",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.JSONField(
                default=list,
                help_text='enclose in square brackets and split into a list of steps like ["1 step", "2 step"]',
            ),
        ),
    ]
