# Generated by Django 4.2.13 on 2024-08-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                help_text="Separate ingredients with a comma and a space",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(
                default="",
                help_text="Number your steps and separate with a semicolon and a space, like '1. step 1; 2. step 2; 3. step 3'. Do not use semicolons within a step",
                max_length=2000,
            ),
        ),
    ]
