# Generated by Django 4.2.13 on 2024-08-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0009_alter_recipe_ingredients_alter_recipe_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(
                default="https://res.cloudinary.com/django-recipe-project/image/upload/v1723008165/blank_image.png",
                upload_to="recipes",
            ),
        ),
    ]
