# Generated by Django 4.2.13 on 2024-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_alter_recipe_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="blank_image.png", upload_to="recipes"),
        ),
    ]
