# Generated by Django 4.2.13 on 2024-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="recipes"),
        ),
    ]
